server:
    port: 8080
spring:
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:file:~/data/mainDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: admin
    jpa:
        database: h2
        hibernate:
            ddl-auto: update
        show-sql: false
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            show-sql: true
            user_sql_comment: false
            format_sql: false